In [ ]:
import os
import pandas as pd 
import numpy as np
file_dir = r'YOURFILEDIR\data'
file_path = os.path.join(file_dir, "export.csv")
df = pd.read_csv(file_path)
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,211507896,2021 Apr 11 12:00:00 AM,2020 Nov 07 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN V,NaN,34.2124,-118.4092
1,201516622,2020 Oct 21 12:00:00 AM,2020 Oct 18 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,2024 Dec 10 12:00:00 AM,2020 Oct 30 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,2020 Dec 24 12:00:00 AM,2020 Dec 24 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,2020 Oct 03 12:00:00 AM,2020 Sep 29 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350

In [2]:
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,1.004894e+06,1.004894e+06,1.004894e+06,1.004894e+06,1.004894e+06,1.004894e+06,1.004894e+06,1.004878e+06,327216.000000,1.004883e+06,69154.000000,2314.000000,64.00000,1.004894e+06,1.004894e+06
mean,2.202190e+08,1.339901e+03,1.069153e+01,1.115613e+03,1.400313e+00,5.001386e+02,2.891862e+01,3.056108e+02,363.950797,4.998992e+02,958.097796,984.015990,991.21875,3.399820e+01,-1.180908e+02
std,1.319070e+07,6.510761e+02,6.110248e+00,6.111596e+02,4.899620e-01,2.052638e+02,2.199267e+01,2.192913e+02,123.737665,2.050643e+02,110.358509,52.350982,27.06985,1.610789e+00,5.582654e+00
min,8.170000e+02,1.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,1.100000e+02,-4.000000e+00,1.010000e+02,101.000000,1.100000e+02,210.000000,310.000000,821.00000,0.000000e+00,-1.186676e+02
25%,2.106168e+08,9.000000e+02,5.000000e+00,5.870000e+02,1.000000e+00,3.310000e+02,0.000000e+00,1.010000e+02,311.000000,3.310000e+02,998.000000,998.000000,998.00000,3.401470e+01,-1.184305e+02
50%,2.209158e+08,1.420000e+03,1.100000e+01,1.139000e+03,1.000000e+00,4.420000e+02,3.000000e+01,2.030000e+02,400.000000,4.420000e+02,998.000000,998.000000,998.00000,3.405890e+01,-1.183225e+02
75%,2.311102e+08,1.900000e+03,1.600000e+01,1.613000e+03,2.000000e+00,6.260000e+02,4.400000e+01,5.010000e+02,400.000000,6.260000e+02,998.000000,998.000000,998.00000,3.416490e+01,-1.182739e+02
max,2.521040e+08,2.359000e+03,2.100000e+01,2.199000e+03,2.000000e+00,9.560000e+02,1.200000e+02,9.760000e+02,516.000000,9.560000e+02,999.000000,999.000000,999.00000,3.433430e+01,0.000000e+00

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004894 entries, 0 to 1004893
Data columns (total 28 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1004894 non-null  int64
 1   Date Rptd       1004894 non-null  object
 2   DATE OCC        1004894 non-null  object
 3   TIME OCC        1004894 non-null  int64
 4   AREA            1004894 non-null  int64
 5   AREA NAME       1004894 non-null  object
 6   Rpt Dist No     1004894 non-null  int64
 7   Part 1-2        1004894 non-null  int64
 8   Crm Cd          1004894 non-null  int64
 9   Crm Cd Desc     1004894 non-null  object
 10  Mocodes         853296 non-null   object
 11  Vict Age        1004894 non-null  int64
 12  Vict Sex        860263 non-null   object
 13  Vict Descent    860251 non-null   object
 14  Premis Cd       1004878 non-null  float64
 15  Premis Desc     1004306 non-null  object
 16  Weapon Used Cd  327216 non-null   float64
 17  Weapon Desc     327216 non-null   object
 18  Status          1004893 non-null  object
 19  Status Desc     1004894 non-null  object
 20  Crm Cd 1        1004883 non-null  float64
 21  Crm Cd 2        69154 non-null    float64
 22  Crm Cd 3        2314 non-null     float64
 23  Crm Cd 4        64 non-null       float64
 24  LOCATION        1004894 non-null  object
 25  Cross Street    154228 non-null   object
 26  LAT             1004894 non-null  float64
 27  LON             1004894 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 214.7+ MB

In [4]:
df.isnull().sum()

DR_NO                   0
Date Rptd               0
DATE OCC                0
TIME OCC                0
AREA                    0
AREA NAME               0
Rpt Dist No             0
Part 1-2                0
Crm Cd                  0
Crm Cd Desc             0
Mocodes            151598
Vict Age                0
Vict Sex           144631
Vict Descent       144643
Premis Cd              16
Premis Desc           588
Weapon Used Cd     677678
Weapon Desc        677678
Status                  1
Status Desc             0
Crm Cd 1               11
Crm Cd 2           935740
Crm Cd 3          1002580
Crm Cd 4          1004830
LOCATION                0
Cross Street       850666
LAT                     0
LON                     0
dtype: int64

In [6]:
# 1. Convert dates to datetime
df['Date Rptd'] = pd.to_datetime(df['Date Rptd'])
df['DATE OCC'] = pd.to_datetime(df['DATE OCC'])

# 2. Fill and convert numeric code columns from float to int
code_columns = ['Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'Weapon Used Cd']

for col in code_columns:
    df[col] = df[col].fillna(0).astype('int64')

In [7]:
df['TIME OCC'] = (
    df['TIME OCC']
    .astype(str)
    .str.replace(r'\.0$', '', regex=True)
    .str.zfill(4) 
)
df['TIME OCC'] = df['TIME OCC'].str.slice(0,2) + ':' + df['TIME OCC'].str.slice(2,4)

In [8]:
df['DATE OCC'] = pd.to_datetime(df['DATE OCC']).dt.date
df['Date Rptd'] = pd.to_datetime(df['Date Rptd']).dt.date

In [9]:
df[['DATE OCC', 'Date Rptd']].head(10)

     DATE OCC   Date Rptd
0  2020-11-07  2021-04-11
1  2020-10-18  2020-10-21
2  2020-10-30  2024-12-10
3  2020-12-24  2020-12-24
4  2020-09-29  2020-10-03
5  2020-11-11  2024-12-11
6  2020-04-16  2024-12-16
7  2020-07-07  2020-10-29
8  2020-03-02  2024-04-20
9  2020-09-01  2024-12-18

In [10]:
df['Mocodes'] = df['Mocodes'].fillna('')

In [11]:
 df['Vict Sex'].unique()

array(['M', 'F', nan, 'X', 'H', '-'], dtype=object)

In [12]:
df['Vict Sex'] = df['Vict Sex'].replace([r'^\s*$', '-'], np.nan, regex=True)
sex_mapping = {
    'M' : 'Male',
    'F' : 'Female',
    'X' : 'Unknown',
    'H' : 'Unknown'
}
df['Vict Sex'] = df['Vict Sex'].map(sex_mapping).fillna('Not Applicable / Unknown')

In [13]:
 df['Vict Descent'].unique()

array(['H', 'W', 'A', 'B', nan, 'X', 'O', 'C', 'J', 'V', 'K', 'F', 'I',
       'Z', 'L', 'G', 'P', 'D', 'U', 'S', '-'], dtype=object)

In [14]:
df['Vict Descent'] = df['Vict Descent'].replace([r'^\s*$', '-'], np.nan, regex=True)
descent_mapping = {
    'A': 'Other Asian',
    'B': 'Black',
    'C': 'Chinese',
    'D': ' Cambodian',
    'F': 'Filipino',
    'G': 'Guamanian',
    'H': 'Hispanic/Latin/Mexican',
    'I': 'American Indian/Alaskan Native',
    'J': 'Japanese',
    'K': 'Korean',
    'L': 'Laotian',
    'O': 'Other',
    'P': 'Pacific Islander',
    'S': 'Samoan',
    'U': 'Hawaiian',
    'V': 'Vietnamese',
    'W': 'White',
    'X': 'Unknown',
    'Z': 'Asian Indian'
}
df['Vict Descent'] = df['Vict Descent'].map(descent_mapping).fillna('Unknown / Not Specified')

In [15]:
df['Vict Descent'].value_counts(dropna=False)

Vict Descent
Hispanic/Latin/Mexican            296370
White                             201429
Unknown / Not Specified           144645
Black                             135809
Unknown                           106661
Other                              78001
Other Asian                        21338
Korean                              5990
Filipino                            4838
Chinese                             4631
Japanese                            1586
Vietnamese                          1195
American Indian/Alaskan Native      1015
Asian Indian                         577
Pacific Islander                     288
Hawaiian                             221
 Cambodian                            91
Laotian                               77
Guamanian                             74
Samoan                                58
Name: count, dtype: int64

In [16]:
valid_premises = df.dropna(subset=['Premis Cd', 'Premis Desc'])
premis_dict = dict(zip(valid_premises['Premis Cd'], valid_premises['Premis Desc']))


df['Premis Desc'] = df['Premis Desc'].fillna(df['Premis Cd'].map(premis_dict))

df['Premis Desc'] = df['Premis Desc'].fillna('UNKNOWN')
df['Premis Cd'] = df['Premis Cd'].fillna('UNKNOWN')

In [17]:
df.isnull().sum()

DR_NO                  0
Date Rptd              0
DATE OCC               0
TIME OCC               0
AREA                   0
AREA NAME              0
Rpt Dist No            0
Part 1-2               0
Crm Cd                 0
Crm Cd Desc            0
Mocodes                0
Vict Age               0
Vict Sex               0
Vict Descent           0
Premis Cd              0
Premis Desc            0
Weapon Used Cd         0
Weapon Desc       677678
Status                 1
Status Desc            0
Crm Cd 1              11
Crm Cd 2               0
Crm Cd 3               0
Crm Cd 4               0
LOCATION               0
Cross Street      850666
LAT                    0
LON                    0
dtype: int64

In [18]:
df['Weapon_Used_Flag'] = (df['Weapon Used Cd'] != 0).astype(int)

In [19]:
df['Weapon Used Cd'] = df['Weapon Used Cd'].fillna(0)

In [20]:
df['Weapon Desc'] = df['Weapon Desc'].fillna('NO WEAPON / NOT APPLICABLE')

In [21]:
 print(df[df['Status'].isnull()][['Status', 'Status Desc']])

       Status Status Desc
882203    NaN         UNK

In [22]:
df['Status Desc'].unique()

array(['Invest Cont', 'Adult Other', 'Adult Arrest', 'Juv Arrest',
       'Juv Other', 'UNK'], dtype=object)

In [23]:
#Creating a lookup
valid_status = df.dropna(subset=['Status', 'Status Desc'])
status_reverse_dict = dict(zip(valid_status['Status Desc'], valid_status['Status']))

df['Status'] = df['Status'].fillna(df['Status Desc'].map(status_reverse_dict))

In [24]:
df.iloc[882203][['Status']]

Status    CC
Name: 882203, dtype: object

In [25]:
filtered_df = df[df['Crm Cd 1'].isnull()][[ 'Crm Cd' ,'Crm Cd Desc', 'Crm Cd 1',]]
print(filtered_df)

        Crm Cd                                        Crm Cd Desc  Crm Cd 1
91235      740  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...       NaN
133312     745           VANDALISM - MISDEAMEANOR ($399 OR UNDER)       NaN
237001     520                           VEHICLE - ATTEMPT STOLEN       NaN
350431     442           SHOPLIFTING - PETTY THEFT ($950 & UNDER)       NaN
432358     890                                   FAILURE TO YIELD       NaN
495781     888                                        TRESPASSING       NaN
508451     888                                        TRESPASSING       NaN
694465     442           SHOPLIFTING - PETTY THEFT ($950 & UNDER)       NaN
705396     330                              BURGLARY FROM VEHICLE       NaN
801499     330                              BURGLARY FROM VEHICLE       NaN
873827     623                            BATTERY POLICE (SIMPLE)       NaN

In [26]:
valid_status = df.dropna(subset=['Crm Cd', 'Crm Cd 1'])
status_reverse_dict = dict(zip(valid_status['Crm Cd 1'], valid_status['Crm Cd']))

df['Crm Cd 1'] = df['Crm Cd 1'].fillna(df['Crm Cd']).map(status_reverse_dict)

In [27]:
df[['Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4',]] = df[['Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4',]].fillna(0)

In [28]:
df['Cross Street'] = df['Cross Street'].fillna('None')

In [29]:
df['LOCATION'] = df['LOCATION'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [30]:
df['DR_NO'].duplicated().sum()

np.int64(0)

In [31]:
# Replace multiple consecutive spaces with a single space and strip edges for CROSS STREET
df['Cross Street'] = df['Cross Street'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [31]:
df.dtypes

DR_NO                        int64
Date Rptd           datetime64[ns]
DATE OCC            datetime64[ns]
TIME OCC                     int64
AREA                         int64
AREA NAME                   object
Rpt Dist No                  int64
Part 1-2                     int64
Crm Cd                       int64
Crm Cd Desc                 object
Mocodes                     object
Vict Age                     int64
Vict Sex                    object
Vict Descent                object
Premis Cd                   object
Premis Desc                 object
Weapon Used Cd               int64
Weapon Desc                 object
Status                      object
Status Desc                 object
Crm Cd 1                     int64
Crm Cd 2                     int64
Crm Cd 3                     int64
Crm Cd 4                     int64
LOCATION                    object
Cross Street                object
LAT                        float64
LON                        float64
Weapon_Used_Flag             int64
dtype: object

In [32]:
df = df.rename(columns={
    'DR_NO' : 'record_no',
    'DATE OCC' : 'date_occurred',
    'Date Rptd': 'date_reported',
    'TIME OCC': 'time_occurred',
    'AREA' : 'area',
    'AREA NAME' : 'area_name',
    'Rpt Dist No' : 'reporting_district_no',
    'Part 1-2' : 'part_1-2',
    'Crm Cd' : 'crime_code',
    'Crm Cd Desc' : 'crime_code_desc',
    'Mocodes' : 'mocodes',
    'Vict Age' : 'vict_age',
    'Vict Sex' : 'vict_sex',
    'Vict Descent' : 'vict_descent',
    'Premis Cd' : 'premis_code',
    'Premis Desc' : 'premis_desc',
    'Weapon Used Cd' : 'weapon_used_code',
    'Weapon Desc' : 'weapon_desc',
    'Status' : 'status',
    'Status Desc' : 'status_desc',
    'Crm Cd 1' : 'crime_code_1',
    'Crm Cd 2' : 'crime_code_2',
    'Crm Cd 3' : 'crime_code_3',
    'Crm Cd 4' : 'crime_code_4',
    'LOCATION' : 'location',
    'Cross Street': 'cross_street',
    'LAT' : 'lat',
    'LON' : 'lon',
    'Weapon_Used_Flag' : 'weapon_used_flag'
})

In [ ]:
# Exporting To SSMS 
import pandas as pd
from sqlalchemy import create_engine

server = r"SERVERNAME\SQLEXPRESS"
database = "CrimeRecords"

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&trusted_connection=yes"
    "&TrustServerCertificate=yes"
)

engine = create_engine(connection_string)

In [34]:
with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [35]:
df.to_sql(
    "lapd_crime_records",
    con=engine,
    schema="dbo",
    if_exists="replace",
    index=False)

62

In [37]:
df.to_csv('lapd_crime_cleaned.csv', index=False)